import type { Metadata } from "next"
import "./globals.css"
import "./styles/mobile.css"  // Added mobile styles
import Provider from "./provider"
import { Nunito } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import { ReactNode } from "react"

const MyAppFont = Nunito({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: 'cover',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <meta name="theme-color" content="#ffffff" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        </head>
        <body className={`${MyAppFont.className} bg-white`}>
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  )
}
